apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: qemu-guest-agent
  name: qemu-guest-agent
  namespace: qemu-ga
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: qemu-guest-agent
  template:
    metadata:
      labels:
        app: qemu-guest-agent
    spec:
      containers:
      - name: qemu-guest-agent
        image: docker.io/jerryhan/qemu-guest-agent:latest
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev
          name: host-dev
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      hostNetwork: true
      hostPID: true
      nodeSelector:
        node.openshift.io/os_id: rhcos
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - SYS_ADMIN
          - SYS_RESOURCE
        privileged: true
#        runAsUser: 0
      serviceAccount: qemu-ga
      serviceAccountName: qemu-ga
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev
        name: host-dev
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
